server:
  port: 8085
  servlet:
    context-path: /terremotos/api
    session:
      timeout: 10m


spring.jpa.properties.hibernate.dialect:  org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      connection-test-query: select 1 from dual
      driver-class-name: com.mysql.cj.jdbc.Driver


    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://b5af5f94f94e86:a9544cec@us-cdbr-iron-east-01.cleardb.net/heroku_c42b6aa5eafb24f?reconnect=true
    username: root
    password: root

logging:
  level:
    ROOT: INFO