server:
  port: 8085
  servlet:
    context-path: /terremotos/api
    session:
      timeout: 10m


spring.jpa.properties.hibernate.dialect:  org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      connection-test-query: select 1 from dual
      driver-class-name: com.mysql.cj.jdbc.Driver


    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/terremotos?createDatabaseIfNotExist=true
    username: root
    password: root
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

logging:
  level:
    ROOT: INFO